export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    features: {
      subdomainStore: true,
      upToProducts: 5,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 1,
      analyticsDays: 7,
      externalFileLinks: true,
      inventoryTracking: false,
      customDomain: false,
      whatsappPay: false,
      digitalDelivery: false,
      storageBandwidth: "200MB",
      professionalTemplate: false,
    },
  },

  go: {
    name: "Go",
    price: 149,
    features: {
      subdomainStore: true,
      upToProducts: 50,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 3,
      analyticsDays: 30,
      externalFileLinks: true,
      inventoryTracking: true,
      digitalDelivery: true,
      digitalDeliveryLimit: 5,
      whatsappPay: true,
      storageBandwidth: "500MB",
      customDomain: false,
      professionalTemplate: false,
    },
  },

  plus: {
    name: "Plus",
    price: 299,
    features: {
      subdomainStore: true,
      upToProducts: 200,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 25,
      analyticsDays: 90,
      externalFileLinks: true,
      inventoryTracking: true,
      customDomain: true,
      digitalDelivery: true,
      digitalDeliveryLimit: 10,
      whatsappPay: true,
      storageBandwidth: "1GB",
      professionalTemplate: false,
    },
  },

  max: {
    name: "Max",
    price: 599,
    features: {
      subdomainStore: true,
      upToProducts: 500,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 25,
      analyticsDays: 365,
      externalFileLinks: true,
      inventoryTracking: true,
      customDomain: true,
      digitalDelivery: true,
      digitalDeliveryLimit: 20,
      whatsappPay: true,
      storageBandwidth: "2GB",
      professionalTemplate: true,
    },
  },
};
