export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    features: {
      subdomainStore: true,
      upToProducts: 10,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 1,
      analyticsDays: 7,
      externalFileLinks: true,
      inventoryTracking: false,
      customDomain: false,
      digitalDelivery: false,
      uploadVideos: false,
    },
  },

  go: {
    name: "Go",
    price: 149,
    features: {
      subdomainStore: true,
      upToProducts: 50,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 3,
      analyticsDays: 30,
      externalFileLinks: true,
      inventoryTracking: true,
      digitalDelivery: true,
      customDomain: false,
      uploadVideos: false,
    },
  },

  plus: {
    name: "Plus",
    price: 299,
    features: {
      subdomainStore: true,
      upToProducts: 200,
      razorpayCheckout: true,
      emailAlerts: true,
      discountCodes: 25,
      analyticsDays: 90,
      externalFileLinks: true,
      inventoryTracking: true,
      customDomain: true,
      digitalDelivery: true,
      uploadVideos: true,
    },
  },
};
